# Generated by Django 4.0.5 on 2022-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default='Hey'),
            preserve_default=False,
        ),
    ]
